## catalog of libraries and plugins used to build and run the Jolt-JNI Project

[versions]

android-ndk = "29.0.14206865"
checkstyle = "13.2.0"

[libraries]

jsnaploader = "io.github.electrostat-lab:snaploader:1.1.1-stable"
junit4 = "junit:junit:4.13.2"
log4j-impl = "org.apache.logging.log4j:log4j-slf4j2-impl:2.25.3"
oshi-core = "com.github.oshi:oshi-core:6.9.3"

[bundles]

[plugins]

android-library = { id = "com.android.library", version = "8.13.2" }
download = { id = "de.undercouch.download", version = "5.7.0" }
